discord:
  token: MTA3ODEwMjgzNDg3NDE2NzM1Ng.GxuBo8.tcjGQ7mRT1cR6cg6QzSMk8kYYYjlx9TIArK7Hg
  punishChannel: 1094686674300190901
  onlinePlayers: 1084496172305092718
database:
  host: localhost
  port: 3306
  database: classicdupe
  username: classicdupe
  password: LNWnNwZHy7xdFMw7rah9